# Generated by Django 4.2.14 on 2024-07-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rest_password_expire',
            new_name='reset_password_expire',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='rest_password_token',
            new_name='reset_password_token',
        ),
    ]
