# Generated by Django 4.2.14 on 2024-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('employee', 'employee')], default='employee', max_length=10),
        ),
    ]
