# Generated by Django 4.2.14 on 2024-07-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='finished',
        ),
        migrations.AddField(
            model_name='step',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Started', 'Started'), ('Finished', 'Finished')], default='To Do', max_length=20),
        ),
    ]
