# Generated by Django 4.2.14 on 2024-07-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_step_finished_step_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='implementation_duration_end',
        ),
        migrations.RemoveField(
            model_name='task',
            name='implementation_duration_start',
        ),
        migrations.AddField(
            model_name='task',
            name='implementation_duration_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
