# Generated by Django 4.2.14 on 2024-07-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_task_implementation_duration_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='implementation_duration_hours',
            field=models.FloatField(default=1.0),
        ),
    ]
